-- Restrict EXECUTE on two orphaned public-schema RPCs.
--
-- Follow-up to #385 / #381. NOT YET APPLIED — apply manually after review.
--
-- ---------------------------------------------------------------------------
-- WHY
-- ---------------------------------------------------------------------------
--
-- 20260820000003_reconcile_function_execute_grants.sql granted EXECUTE on
-- get_user_points(uuid) and recalculate_member_points(uuid) to `authenticated`,
-- because both were anon-executable and moving them behind auth was a strict
-- improvement. Review of that migration flagged that neither function has a
-- definition anywhere in this repository, so their bodies could not be checked.
--
-- They have since been read out of the live database with pg_get_functiondef.
-- Both are orphans: no caller in src/, none in supabase/functions/, no
-- CREATE FUNCTION in supabase/migrations/. What the bodies show:
--
--   recalculate_member_points(p_member_id uuid)
--     SECURITY DEFINER, SET search_path TO 'public', and NO authorization
--     guard of any kind -- no is_admin_user(), no auth.uid() check. It writes
--     public.members.points and public.members.events_attended for whatever
--     member id the caller passes, bypassing RLS because it is DEFINER.
--
--     It recomputes from public.member_event_attendance rather than accepting a
--     value, so a caller cannot invent points. The exposure is narrower than it
--     first looks. But it is still an unauthenticated-in-spirit write primitive
--     over ANOTHER member's row, callable by any signed-in user, against a
--     protected domain (points). It also silently clobbers any manual points
--     adjustment an admin has made.
--
--   get_user_points(uid uuid)
--     SECURITY INVOKER, STABLE, so RLS still applies to the caller. Materially
--     lower risk. It reads the LEGACY points path (public.check_ins joined to
--     public.events), not the members ledger, so it is also almost certainly
--     dead code from the pre-members points system.
--
-- ---------------------------------------------------------------------------
-- WHAT THIS DOES
-- ---------------------------------------------------------------------------
--
-- Removes EXECUTE from every client role on both. Neither has a caller, so
-- nothing in the app can break. service_role and postgres are unaffected and
-- retain access, so any admin/server-side use keeps working.
--
-- Deliberately NOT dropping either function. Dropping is a separate decision
-- that belongs with the schema-drift half of #381, and a DROP is the one thing
-- here that would be painful to undo.
--
-- Forward-only. Do not edit this file; write a new migration to adjust.

begin;

-- Protected-domain write primitive with no internal guard. No caller in src/.
revoke execute on function public.recalculate_member_points(uuid) from public, anon, authenticated;

-- Legacy points read path (check_ins). No caller in src/.
revoke execute on function public.get_user_points(uuid) from public, anon, authenticated;

comment on function public.recalculate_member_points(uuid) is
  'Orphaned SECURITY DEFINER points recalculation with no authorization guard. '
  'EXECUTE revoked from all client roles (#381 follow-up); service_role only. '
  'Has no definition in supabase/migrations/ -- reconcile or drop.';

comment on function public.get_user_points(uuid) is
  'Orphaned legacy points lookup over public.check_ins. EXECUTE revoked from '
  'all client roles (#381 follow-up). Has no definition in supabase/migrations/.';

commit;

-- ---------------------------------------------------------------------------
-- VERIFY AFTER APPLYING
-- ---------------------------------------------------------------------------
--
-- Expect zero rows for both roles:
--
--   select p.proname, r.rolname
--   from pg_proc p
--   join pg_namespace n on n.oid = p.pronamespace
--   cross join (values ('anon'),('authenticated')) as r(rolname)
--   where n.nspname = 'public'
--     and p.proname in ('get_user_points','recalculate_member_points')
--     and has_function_privilege(r.rolname, p.oid, 'EXECUTE');
--
-- Then confirm the admin Members and Points pages still work -- neither calls
-- these, so this is a regression check rather than an expected change.
