-- Restrict anonymous SELECT on public.events to an explicit column allowlist.
--
-- Issue: #379 (found by the #226 anon-key exposure audit).
--
-- WHY
-- ---
-- `events.check_in_form_url` has been anon-selectable since the table was
-- created in 20240320000002_create_missing_tables.sql, which predates every
-- security-hardening migration in this repo. The audit found live non-empty
-- values reachable through the public PostgREST read path.
--
-- The column is edited only from the admin Events UI and is never rendered on a
-- public page. A public check-in form URL is an operational attendance surface
-- that visitors do not need, and distributing it through the public database API
-- offers a path toward attendance outside the server-authoritative
-- `check_in_to_event` RPC (see 20260620000000_move_check_in_code_to_secrets_table.sql).
--
-- HOW
-- ---
-- A column-level REVOKE cannot override a table-level SELECT grant, so hiding a
-- single column requires revoking the table grant and re-granting only the safe
-- columns. This mirrors the established pattern applied to `public.members` in
-- 20260619040000_minimize_public_member_exposure.sql.
--
-- `authenticated` deliberately keeps its table-level SELECT: the admin Events
-- pages create and edit `check_in_form_url`, and src/hooks/useEventAttendance.ts
-- reads it back on the signed-in member's own attendance rows.
--
-- Forward-only. Do not edit this file; write a new migration to adjust.

-- Cut anon's table-wide read, then re-grant every column EXCEPT
-- check_in_form_url. The list below is the full live column set for
-- public.events as assembled from this repo's migration history:
--   20240320000002 (base), 20240320000004 (event_type),
--   20240320000011 (image_url), 20240320000012 (is_code_expired),
--   20260512000000 (academic_term_id), 20260526000000 (thumbnail_url),
--   20260529000000 (start_time, end_time), 20260529010000 (end_date),
--   20260602000000 (is_published). check_in_code was dropped in 20260620000000.
revoke select on public.events from anon;

grant select (
  id,
  name,
  description,
  date,
  start_time,
  end_time,
  end_date,
  location,
  points,
  event_type,
  image_url,
  thumbnail_url,
  is_code_expired,
  is_published,
  academic_term_id,
  created_at,
  updated_at
) on public.events to anon;

comment on column public.events.check_in_form_url is
  'Admin-only operational check-in URL. Never granted to anon (#379). Read by '
  'admin Events pages and by useEventAttendance for the signed-in member''s own '
  'attendance rows, both of which run as authenticated.';
