-- Event flyer for standalone external events.
--
-- WHY
-- ---
-- /uvsa-network Upcoming Externals is flyer-forward, like /events. A listing
-- that mirrors a normal event (source_event_id) reuses that event's
-- thumbnail_url / image_url, so the flyer is never uploaded twice. Standalone
-- listings (historical rows, rows entered in Admin -> External Events) have no
-- event to borrow from and external_events had no image column of its own.
--
-- `image_url` is that flyer. It is deliberately separate from the school's
-- `logo_url` (the circular Instagram PFP) and `image_url` (the school card
-- photo): a school logo and an event flyer serve different purposes.
--
-- ACCESS
-- ------
-- Row policies are unchanged. Anon's column allowlist (20260820000002,
-- extended by 20261002060000) gains exactly this one column; it is a public
-- flyer URL, not editorial data. Admin writes already go through the existing
-- admin policy.
--
-- Forward-only. Do not edit this file; write a new migration to adjust.

alter table public.external_events
  add column image_url text;

grant select (image_url) on public.external_events to anon;

comment on column public.external_events.image_url is
  'Event flyer for listings without a source_event_id (linked listings use the source event''s image). Not the school logo.';
