-- Point every UVSA school at its current Instagram profile.
--
-- The school logo / PFP on /uvsa-network now links to `uvsa_schools.instagram_url`,
-- so those URLs need to be the canonical profile links. Rows are matched on the
-- stable `slug`, never on name. Nothing else about a school is changed.
--
-- A slug that does not exist in a given database is skipped with a NOTICE rather
-- than failing the migration.
--
-- Forward-only. Do not edit this file; write a new migration to adjust.

do $$
declare
  mapping record;
begin
  for mapping in
    select * from (values
      ('ucsd',    'https://www.instagram.com/vsaatucsd/'),
      ('usc',     'https://www.instagram.com/uscvsa/'),
      ('cpp',     'https://www.instagram.com/cpp.vsa/'),
      ('chapman', 'https://www.instagram.com/chapmanvsa/'),
      ('ucr',     'https://www.instagram.com/ucrvsa/'),
      ('uci',     'https://www.instagram.com/vsauci/'),
      ('sdsu',    'https://www.instagram.com/sdsuvsa/'),
      ('ucsb',    'https://www.instagram.com/ucsbvsa/'),
      ('csusm',   'https://www.instagram.com/csusmvsa/'),
      ('csuf',    'https://www.instagram.com/csufvsa/'),
      ('csulb',   'https://www.instagram.com/lbvsa/'),
      ('cpslo',   'https://www.instagram.com/calpolyvsa/'),
      ('csun',    'https://www.instagram.com/csun_seasa/')
    ) as v(slug, instagram_url)
  loop
    update public.uvsa_schools
       set instagram_url = mapping.instagram_url
     where slug = mapping.slug
       and instagram_url is distinct from mapping.instagram_url;

    if not exists (select 1 from public.uvsa_schools where slug = mapping.slug) then
      raise notice 'uvsa_schools slug % not found; skipped', mapping.slug;
    end if;
  end loop;
end
$$;
