-- Public storage bucket for UVSA school logos / Instagram profile pictures.
--
-- WHY
-- ---
-- `/admin/uvsa-schools` previously exposed only a raw "Logo URL" text field, and
-- the public page refused every Supabase Storage URL, so admins had no way to
-- upload a logo. This adds a narrowly scoped bucket for exactly that: one small
-- square image per school, stored under `<school-slug>/` and referenced from the
-- existing `uvsa_schools.logo_url` column (no schema change).
--
-- ACCESS MODEL
-- ------------
--   read    public by URL — the bucket's `public` flag serves objects without any
--           storage.objects policy. SELECT on storage.objects is admin-only, so
--           anonymous clients cannot LIST the bucket (which would expose
--           uploads that were never saved onto a school).
--   write   admins only — insert and update, gated on is_admin_user()
--   delete  intentionally has NO policy: the repo never deletes Storage files,
--           and the client never needs to. Add one in a new migration if that
--           ever changes.
--
-- The bucket is constrained to raster images the client already produces
-- (`prepareImageForUpload(file, 'logo')` => <=512px webp). SVG is deliberately
-- excluded: a public bucket serving user-supplied SVG can carry script.
-- The 5 MB cap matches the client-side input limit for the `logo` preset.
--
-- Forward-only. Do not edit this file; write a new migration to adjust.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'uvsa_school_assets',
  'uvsa_school_assets',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
  set public = true,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Admins can list uvsa school assets" on storage.objects;
create policy "Admins can list uvsa school assets"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'uvsa_school_assets'
    and public.is_admin_user(auth.uid())
  );

drop policy if exists "Admins can upload uvsa school assets" on storage.objects;
create policy "Admins can upload uvsa school assets"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'uvsa_school_assets'
    and public.is_admin_user(auth.uid())
  );

drop policy if exists "Admins can update uvsa school assets" on storage.objects;
create policy "Admins can update uvsa school assets"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'uvsa_school_assets'
    and public.is_admin_user(auth.uid())
  )
  with check (
    bucket_id = 'uvsa_school_assets'
    and public.is_admin_user(auth.uid())
  );
