-- Revoke anonymous SELECT on the raw attendance ledger.
--
-- Issue: #380 (found by the #226 anon-key exposure audit).
--
-- WHY
-- ---
-- 20260711014000_create_member_event_history_view.sql introduced
-- `member_event_history` as the deliberate public surface for individual
-- attendance, and its header states the base table "was not exposed to
-- anon/authenticated at all". src/data/repos/leaderboard.ts carries the same
-- belief in a comment.
--
-- That was never true. `public.member_event_attendance` has no REVOKE anywhere
-- in this repo's migration history, so Supabase's default privileges left it
-- readable by anon from creation. The audit confirmed all live rows, including
-- `imported_at`, were anon-selectable.
--
-- Two problems follow. The base table bypasses the view's `is_published` filter,
-- so attendance for unpublished events is reachable; and it creates a second,
-- undocumented public contract, meaning any column added to the ledger later
-- becomes public automatically.
--
-- This migration changes access only. It does not touch attendance rows, points
-- calculation, or leaderboard calculation (protected domains, AGENTS.md).
--
-- `authenticated` deliberately keeps table-level SELECT: the admin Import,
-- Members, and Points pages read the raw ledger, including `imported_at`, for
-- import review and merge tooling.
--
-- Forward-only. Do not edit this file; write a new migration to adjust.

revoke select on public.member_event_attendance from anon;

comment on table public.member_event_attendance is
  'Raw attendance ledger (protected domain). Not readable by anon (#380) — the '
  'public surface is public.member_event_history, which filters to published '
  'events and omits import metadata. authenticated retains SELECT for admin '
  'import/merge tooling.';

-- The view's original migration granted SELECT without first revoking, so it
-- still carries whatever Supabase's default privileges attached at creation.
-- Apply the mandatory revoke-all-then-grant-select pattern (see
-- .claude/skills/vsa-supabase-security-reference §2) so the view's own grants
-- are exactly what we intend and nothing can be written through it.
revoke all on public.member_event_history from anon, authenticated;
grant select on public.member_event_history to anon, authenticated;
