-- Restrict anonymous SELECT on the UVSA network tables to public columns.
--
-- Issue: #382 (found by the #226 anon-key exposure audit).
--
-- WHY
-- ---
-- `uvsa_schools` and `external_events` are read by public pages, and their
-- policies expose the whole row. Four columns are internal editorial metadata:
--
--   uvsa_schools.verification_notes    uvsa_schools.confidence_level
--   external_events.source_notes       external_events.confidence_level
--
-- All four are null in every live public row today, so nothing has leaked. They
-- are edited only from admin pages, though, and both tables are read with
-- `select('*')` — so the first note anyone writes becomes public immediately,
-- with no code change to signal it. This closes the hole before it opens.
--
-- HOW
-- ---
-- A column-level REVOKE cannot override a table-level SELECT grant, so this
-- revokes anon's table grant and re-grants the public columns explicitly — the
-- same pattern used for `public.members` in 20260619040000 and for
-- `public.events` in 20260820000000.
--
-- `authenticated` keeps table-level SELECT so admin UVSA pages continue to read
-- and edit the full rows. Draft `external_events` remain governed by the
-- existing row-level policy; this migration changes column access only and does
-- not alter any policy.
--
-- Forward-only. Do not edit this file; write a new migration to adjust.

revoke select on public.uvsa_schools from anon;

grant select (
  id,
  school_name,
  short_name,
  slug,
  system_type,
  city,
  vsa_name,
  instagram_url,
  linktree_url,
  website_url,
  facebook_url,
  youtube_url,
  tiktok_url,
  description,
  known_for,
  recurring_events,
  logo_url,
  image_url,
  is_active,
  sort_order,
  created_at,
  updated_at
) on public.uvsa_schools to anon;

revoke select on public.external_events from anon;

grant select (
  id,
  uvsa_school_id,
  title,
  event_type,
  date,
  academic_term_id,
  location,
  description,
  points,
  rsvp_url,
  ride_form_url,
  instagram_url,
  host_info_url,
  ride_info,
  status,
  photo_album_url,
  recap,
  is_featured,
  created_at,
  updated_at
) on public.external_events to anon;

comment on column public.uvsa_schools.verification_notes is
  'Internal editorial note. Never granted to anon (#382).';
comment on column public.uvsa_schools.confidence_level is
  'Internal editorial confidence rating. Never granted to anon (#382).';
comment on column public.external_events.source_notes is
  'Internal sourcing note. Never granted to anon (#382).';
comment on column public.external_events.confidence_level is
  'Internal editorial confidence rating. Never granted to anon (#382).';
