-- Link external_events to normal events and allow UVSA SoCal as a host.
--
-- WHY
-- ---
-- Admin -> Events now owns the whole external workflow: choosing Event Type =
-- External Event reveals the host and event-link fields and keeps exactly one
-- `external_events` row in step with the event, so /uvsa-network picks it up
-- with no second data-entry step. This migration adds the three columns that
-- makes that possible.
--
--   host_type         'school' (default, every existing row) or 'uvsa_socal'.
--                     UVSA SoCal is not one of the 13 schools, so it never gets
--                     a fake uvsa_schools row; a UVSA-hosted row simply has no
--                     school.
--   source_event_id   Optional link to the normal event this listing mirrors.
--                     UNIQUE, so an event has at most one listing and the admin
--                     save can upsert on it idempotently. NULL for externals
--                     that are not mirrored as VSA events (historical rows,
--                     rows entered in Admin -> External Events).
--                     ON DELETE CASCADE: deleting the event removes its mirror.
--   show_on_network   The admin's "Show on UVSA Network" choice, kept so an
--                     unpublished or retyped event can reopen with the choice
--                     intact. The listing is hidden by status = 'draft', which
--                     the existing public RLS policy already filters out.
--
-- `uvsa_school_id` is deliberately NOT forced non-null for school hosts at the
-- database level: its foreign key is ON DELETE SET NULL, so deleting a school
-- must remain possible. Rows that lose their school surface as "Host missing"
-- in Admin instead, and the admin form requires a school for school-hosted
-- events. The reverse rule IS enforced here: a UVSA SoCal listing has no school.
--
-- ACCESS
-- ------
-- Row policies are unchanged (public reads non-draft rows, admins manage all).
-- Anon's column allowlist from 20260820000002 is extended by exactly two
-- columns, host_type and source_event_id, both non-sensitive: the event id is
-- already public on /events. Public pages need source_event_id to look up the
-- listing for an event. show_on_network is admin-only and is NOT granted.
--
-- Existing event_type = 'external_event' events are not auto-linked; creating a
-- listing needs a host, and guessing one would invent data.
--
-- Forward-only. Do not edit this file; write a new migration to adjust.

alter table public.external_events
  add column host_type text not null default 'school',
  add column source_event_id uuid references public.events (id) on delete cascade,
  add column show_on_network boolean not null default true;

alter table public.external_events
  add constraint external_events_host_type_check
    check (host_type in ('school', 'uvsa_socal')),
  add constraint external_events_uvsa_socal_has_no_school
    check (host_type <> 'uvsa_socal' or uvsa_school_id is null);

-- A plain (non-partial) unique index so PostgREST can upsert with
-- on_conflict=source_event_id. NULLs are distinct, so unlinked rows are free.
create unique index external_events_source_event_id_key
  on public.external_events (source_event_id);

grant select (host_type, source_event_id) on public.external_events to anon;

comment on column public.external_events.host_type is
  'school = hosted by uvsa_school_id; uvsa_socal = hosted by UVSA SoCal (no school row).';
comment on column public.external_events.source_event_id is
  'The normal events row this listing mirrors; unique. Cascade-deleted with the event.';
comment on column public.external_events.show_on_network is
  'Admin choice to list the linked event on /uvsa-network. Hidden listings use status = draft. Never granted to anon.';
