-- Revoke client EXECUTE on trigger functions, make #385's revokes replayable,
-- and pin the remaining mutable search_paths.
--
-- Closes #396. NOT YET APPLIED — apply manually after review.
--
-- ---------------------------------------------------------------------------
-- WHY
-- ---------------------------------------------------------------------------
--
-- 1. Trigger functions are callable as RPCs by any signed-in user.
--    20260820000003_reconcile_function_execute_grants.sql revoked them from
--    `public` and `anon` but not `authenticated`. Email sign-up is open (#429),
--    so `authenticated` is a role anyone can obtain. A direct call fails
--    without trigger context, so the practical risk is low, but two of them
--    (sync_member_points, sync_attendance_points_on_event_update) sit in the
--    points domain and several are SECURITY DEFINER. Triggers do not need the
--    invoking role to hold EXECUTE: PostgreSQL checks EXECUTE on the trigger
--    function only at CREATE TRIGGER time, so revoking it changes nothing about
--    how the triggers fire.
--
--    This is done with a catalog loop over every public function that returns
--    `trigger`, rather than a hand-written list, so it covers live-only trigger
--    functions (check_achievements, sync_member_points) and is a no-op for any
--    that do not exist on a clean rebuild.
--
-- 2. 20260820000003 is not replayable. It revokes EXECUTE on functions that
--    exist only in production, so on a database rebuilt from this chain it
--    raises undefined_function and aborts. Forward-only rules mean it cannot
--    be edited; this migration re-applies its non-trigger revokes behind
--    to_regprocedure guards, so the end state is the same on either path.
--
-- 3. Six SECURITY INVOKER trigger functions have a mutable search_path. Each
--    body was read from production before writing this: every table reference
--    is schema-qualified (public.vcn_archives, public.house_memberships) and the
--    only other calls are auth.uid() and pg_catalog built-ins (now, coalesce,
--    daterange), so search_path = '' is safe for all six.
--
-- 4. handle_new_user and handle_new_user_points are SECURITY DEFINER with
--    search_path pinned to `public` in production but not in the tracked
--    chain. Pinned here to the same value production has, via ALTER so the
--    bodies are untouched.
--
-- Forward-only. Do not edit this file; write a new migration to adjust.

begin;

-- 1. Trigger functions: no client role needs EXECUTE.
do $triggers$
declare
  fn regprocedure;
begin
  for fn in
    select p.oid::regprocedure
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.prorettype = 'trigger'::regtype
  loop
    execute format('revoke execute on function %s from public, anon, authenticated', fn);
  end loop;
end
$triggers$;

-- 2. Replayable versions of 20260820000003's revokes on live-only, non-trigger
--    functions. get_user_points and recalculate_member_points were already
--    locked down further by 20260910000000; repeating from public/anon is
--    harmless there and needed on a rebuild.
do $guard$
declare
  sig text;
begin
  foreach sig in array array[
    'public.generate_check_in_code()',
    'public.get_user_points(uuid)',
    'public.recalculate_member_points(uuid)'
  ]
  loop
    if to_regprocedure(sig) is not null then
      execute format('revoke execute on function %s from public, anon', sig);
    else
      raise notice '% not present; skipping.', sig;
    end if;
  end loop;
end
$guard$;

-- 3 + 4. search_path pins, guarded for the same reason.
do $pins$
declare
  pin record;
begin
  for pin in
    select * from (values
      ('public.update_updated_at_column()', ''),
      ('public.handle_updated_at()', ''),
      ('public.ensure_single_current_vcn_archive()', ''),
      ('public.set_resource_link_audit_fields()', ''),
      ('public.set_application_link_audit_fields()', ''),
      ('public.prevent_overlapping_house_memberships()', ''),
      ('public.handle_new_user()', 'public'),
      ('public.handle_new_user_points()', 'public')
    ) as t(sig, path)
  loop
    if to_regprocedure(pin.sig) is not null then
      execute format('alter function %s set search_path = %L', pin.sig, pin.path);
    else
      raise notice '% not present; skipping.', pin.sig;
    end if;
  end loop;
end
$pins$;

-- Record the intent for the one table with RLS and no policies (#396): it is
-- written only by the vsa-ai-assistant Edge Function with the service role.
comment on table public.ai_chat_usage_logs is
  'Ask VSA usage/rate-limit log. Service-role only: RLS is enabled with no '
  'policies on purpose, so no client role can read or write it.';

commit;

-- ---------------------------------------------------------------------------
-- VERIFY AFTER APPLYING
-- ---------------------------------------------------------------------------
--
-- Expect zero rows: no trigger function executable by a client role.
--
--   select p.oid::regprocedure, r.rolname
--   from pg_proc p
--   join pg_namespace n on n.oid = p.pronamespace
--   cross join (values ('anon'), ('authenticated')) as r(rolname)
--   where n.nspname = 'public'
--     and p.prorettype = 'trigger'::regtype
--     and has_function_privilege(r.rolname, p.oid, 'EXECUTE');
--
-- Expect zero rows: no public function with a mutable search_path.
--
--   select p.oid::regprocedure
--   from pg_proc p
--   join pg_namespace n on n.oid = p.pronamespace
--   where n.nspname = 'public'
--     and not exists (
--       select 1 from unnest(coalesce(p.proconfig, '{}')) c
--       where c like 'search_path=%'
--     );
--
-- Then, as an admin, edit an event and save a House membership: both fire
-- triggers covered here and must still succeed.
